# Generated by Django 4.0.4 on 2022-05-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0011_alter_student_regd_no_alter_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=10, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.block')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('permission', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Granted', 'Granted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remark_by_caretaker', models.CharField(max_length=255, null=True)),
                ('remark_by_warden', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('Local', 'Local'), ('Non-Local', 'Non-Local')], max_length=9)),
                ('parent_consent', models.CharField(choices=[('Accepted', 'Accepted'), ('Denied', 'Denied')], default='NA', max_length=8)),
                ('place_of_visit', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
            options={
                'ordering': ['-fromDate'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False, null=True)),
                ('amount_paid', models.FloatField(blank=True, default=0, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=64, null=True)),
                ('dop', models.DateField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.FileField(blank=True, null=True, upload_to='')),
                ('undertaking_form', models.FileField(blank=True, null=True, upload_to='')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='')),
                ('day_scholar_affidavit', models.FileField(blank=True, null=True, upload_to='')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_dates', models.TextField(blank=True, null=True)),
                ('absent_dates', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
    ]
