# Generated by Django 4.0.4 on 2022-10-19 13:28

from django.db import migrations, models
import django.db.models.deletion
import institute.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('permission', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Granted', 'Granted'), ('Rejected', 'Rejected'), ('Revoked', 'Revoked'), ('Pending Extension', 'Pending Extension'), ('Processing Extension', 'Processing Extension'), ('Extension Granted', 'Extension Granted'), ('Extension Rejected', 'Extension Rejected')], default='Pending', max_length=20)),
                ('remark_by_caretaker', models.TextField(null=True)),
                ('remark_by_warden', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Local', 'Local'), ('Non-Local', 'Non-Local'), ('Emergency', 'Emergency'), ('Vacation', 'Vacation')], max_length=9)),
                ('parent_consent', models.CharField(choices=[('Accepted', 'Accepted'), ('Denied', 'Denied')], default='NA', max_length=8)),
                ('place_of_visit', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('In Outing', 'In Outing'), ('Closed', 'Closed')], default='NA', max_length=9)),
                ('mode_of_journey_from', models.CharField(default='NA', max_length=10)),
                ('mode_of_journey_to', models.CharField(default='NA', max_length=10)),
                ('emergency_contact', models.CharField(default=0, max_length=10, validators=[institute.validators.numeric_only])),
                ('mess_rebate', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=9)),
                ('mess_rebate_status', models.CharField(choices=[('Processed', 'Processed'), ('Rejected', 'Rejected')], default='NA', max_length=9)),
                ('mess_rebate_days', models.IntegerField(default=0)),
                ('mess_rebate_remarks', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(null=True, unique=True)),
                ('emergency_medical_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.medicalissue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
            options={
                'ordering': ['-fromDate'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=10, null=True)),
                ('allotted_on', models.DateField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.block')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacated_on', models.DateTimeField()),
                ('mode_of_journey', models.CharField(max_length=255)),
                ('journey_destination', models.CharField(max_length=255)),
                ('iron_cot_status', models.CharField(choices=[('Functioning', 'Functioning'), ('Defective', 'Defective')], max_length=11)),
                ('tube_light_status', models.CharField(choices=[('Functioning', 'Functioning'), ('Defective', 'Defective')], max_length=11)),
                ('fan_status', models.CharField(choices=[('Functioning', 'Functioning'), ('Defective', 'Defective')], max_length=11)),
                ('fan_regulator_status', models.CharField(choices=[('Functioning', 'Functioning'), ('Defective', 'Defective')], max_length=11)),
                ('cupboards_status', models.CharField(choices=[('Functioning', 'Functioning'), ('Defective', 'Defective')], max_length=11)),
                ('switches_status', models.CharField(choices=[('Functioning', 'Functioning'), ('Defective', 'Defective')], max_length=11)),
                ('amperes_socket_15_status', models.CharField(choices=[('Functioning', 'Functioning'), ('Defective', 'Defective')], max_length=11)),
                ('iron_cot_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('tube_light_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('fan_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('fan_regulator_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('cupboards_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('switches_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('amperes_socket_15_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('room_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.roomdetail')),
                ('vacation_outing_obj', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.outing')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False, null=True)),
                ('amount_paid', models.FloatField(blank=True, default=0, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=64, null=True)),
                ('dop', models.DateField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendOuting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('parent_consent', models.CharField(choices=[('Accepted', 'Accepted'), ('Denied', 'Denied')], default='NA', max_length=8)),
                ('permission', models.CharField(choices=[('Pending Extension', 'Pending Extension'), ('Processing Extension', 'Processing Extension'), ('Extension Granted', 'Extension Granted'), ('Extension Rejected', 'Extension Rejected')], default='Pending Extension', max_length=20)),
                ('place_of_visit', models.CharField(max_length=255)),
                ('mode_of_journey_from', models.CharField(max_length=10)),
                ('mode_of_journey_to', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=10, validators=[institute.validators.numeric_only])),
                ('emergency_medical_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.medicalissue')),
                ('outing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.outing')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.FileField(blank=True, null=True, upload_to='')),
                ('undertaking_form', models.FileField(blank=True, null=True, upload_to='')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='')),
                ('day_scholar_affidavit', models.FileField(blank=True, null=True, upload_to='')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_dates', models.TextField(blank=True, null=True)),
                ('absent_dates', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute.student')),
            ],
        ),
    ]
