# Generated by Django 4.0.4 on 2022-05-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='permission',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Granted', 'Granted'), ('Rejected', 'Rejected'), ('Revoked', 'Revoked')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='outing',
            name='type',
            field=models.CharField(choices=[('Local', 'Local'), ('Non-Local', 'Non-Local'), ('Emergency', 'Emergency')], max_length=9),
        ),
    ]
