# Generated by Django 4.0.4 on 2022-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_outing_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='permission',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Granted', 'Granted'), ('Rejected', 'Rejected'), ('Revoked', 'Revoked'), ('In Outing', 'In Outing'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
