# Generated by Django 4.0.4 on 2022-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_extendouting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outing',
            options={'managed': False, 'ordering': ['-fromDate']},
        ),
        migrations.AlterField(
            model_name='extendouting',
            name='permission',
            field=models.CharField(choices=[('Pending Extension', 'Pending Extension'), ('Processing Extension', 'Processing Extension'), ('Extension Granted', 'Extension Granted'), ('Extension Rejected', 'Extension Rejected')], default='Pending Extension', max_length=20),
        ),
    ]
