# Generated by Django 4.0.4 on 2022-06-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_outing_options_alter_extendouting_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outing',
            options={'managed': True, 'ordering': ['-fromDate']},
        ),
    ]
