# Generated by Django 4.0.4 on 2022-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_outing_mess_rebate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='remark_by_caretaker',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outing',
            name='remark_by_warden',
            field=models.TextField(null=True),
        ),
    ]
