# Generated by Django 4.0.4 on 2022-06-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_outing_remark_by_caretaker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendouting',
            name='remark_by_caretaker',
        ),
        migrations.RemoveField(
            model_name='extendouting',
            name='remark_by_warden',
        ),
    ]
