# Generated by Django 4.0.4 on 2022-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_extendouting_remark_by_caretaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='mess_rebate_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outing',
            name='mess_rebate_status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Rejected', 'Rejected')], default='NA', max_length=9),
        ),
    ]
