# Generated by Django 4.0.4 on 2022-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_outing_mess_rebate_remarks_outing_mess_rebate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='mess_rebate_days',
            field=models.IntegerField(default=0),
        ),
    ]
