# Generated by Django 4.0.4 on 2022-06-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_roomdetail_allotted_at_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
