# Generated by Django 4.0.4 on 2022-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_vacation_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacated_on',
            field=models.DateTimeField(),
        ),
    ]
