# Generated by Django 4.0.4 on 2022-06-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_outing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vacation_outing_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.outing'),
        ),
    ]
