# Generated by Django 4.0.4 on 2022-06-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_vacation_vacation_outing_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetail',
            old_name='allotted_at',
            new_name='allotted_on',
        ),
    ]
