# Generated by Django 4.0.4 on 2022-07-03 16:49

from django.db import migrations, models
import institute.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_remove_attendance_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='emergency_contact',
            field=models.CharField(blank=True, default=0, max_length=10, validators=[institute.validators.numeric_only]),
        ),
        migrations.AddField(
            model_name='outing',
            name='mode_of_journey_from',
            field=models.CharField(blank=True, default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='outing',
            name='mode_of_journey_to',
            field=models.CharField(blank=True, default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='allotted_on',
            field=models.DateField(auto_now=True),
        ),
    ]
