# Generated by Django 4.0.4 on 2022-07-03 16:54

from django.db import migrations, models
import institute.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_outing_emergency_contact_outing_mode_of_journey_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='emergency_contact',
            field=models.CharField(default=0, max_length=10, validators=[institute.validators.numeric_only]),
        ),
        migrations.AlterField(
            model_name='outing',
            name='mode_of_journey_from',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='outing',
            name='mode_of_journey_to',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
