# Generated by Django 4.0.4 on 2022-07-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_medicalissue_status'),
        ('students', '0026_alter_outing_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='emergency_medical_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.medicalissue'),
        ),
    ]
