# Generated by Django 4.0.4 on 2022-07-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_medicalissue_status'),
        ('students', '0028_alter_outing_emergency_medical_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='emergency_medical_issue',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.medicalissue'),
        ),
    ]
