# Generated by Django 4.0.4 on 2022-07-04 16:21

from django.db import migrations, models
import django.db.models.deletion
import institute.validators


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_medicalissue_file'),
        ('students', '0029_alter_outing_emergency_medical_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendouting',
            name='emergency_contact',
            field=models.CharField(default=0, max_length=10, validators=[institute.validators.numeric_only]),
        ),
        migrations.AddField(
            model_name='extendouting',
            name='emergency_medical_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.medicalissue'),
        ),
        migrations.AddField(
            model_name='extendouting',
            name='mode_of_journey_from',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='extendouting',
            name='mode_of_journey_to',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
