# Generated by Django 4.0.4 on 2022-07-04 16:22

from django.db import migrations, models
import institute.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_extendouting_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendouting',
            name='emergency_contact',
            field=models.CharField(max_length=10, validators=[institute.validators.numeric_only]),
        ),
        migrations.AlterField(
            model_name='extendouting',
            name='mode_of_journey_from',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='extendouting',
            name='mode_of_journey_to',
            field=models.CharField(max_length=10),
        ),
    ]
