# Generated by Django 4.0.4 on 2022-07-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_medicalissue_file'),
        ('students', '0031_alter_extendouting_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='emergency_medical_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.medicalissue'),
        ),
    ]
