# Generated by Django 4.0.4 on 2022-06-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_security',
            field=models.BooleanField(default=False),
        ),
    ]
