# Generated by Django 4.0.4 on 2022-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='designation',
            field=models.CharField(choices=[('Superintendent', 'Superintendent'), ('Chief', 'Chief')], max_length=50),
        ),
    ]
