# Generated by Django 4.0.4 on 2022-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_security_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='outinginouttimes',
            name='remark_by_security',
            field=models.TextField(null=True),
        ),
    ]
