# Generated by Django 4.0.4 on 2022-10-19 13:28

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('detailed', models.TextField()),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=complaints.models.Complaint.complaint_file_storage)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Registered', max_length=20)),
                ('summary', models.CharField(max_length=200)),
                ('detailed', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('emergency_outing_permission', models.CharField(choices=[('NA', '----------'), ('Allow', 'Allow'), ('Disallow', 'Disallow')], default='NA', max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to=complaints.models.MedicalIssue.medical_issue_file_storage)),
            ],
        ),
    ]
