# Generated by Django 4.0.4 on 2022-06-19 11:57

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20201121_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=complaints.models.Complaint.complaint_file_storage),
        ),
    ]
