# Generated by Django 4.0.4 on 2022-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_medicalissue_emergency_outing_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalissue',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Registered', max_length=20),
        ),
    ]
