# Generated by Django 4.0.4 on 2022-07-04 15:48

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_medicalissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalissue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=complaints.models.MedicalIssue.medical_issue_file_storage),
        ),
    ]
