# Generated by Django 4.0.4 on 2022-10-19 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import institute.models
import institute.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('1S', 'One student per Room'), ('2S', 'Two students per Room'), ('4S', 'Four students per Room')], max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('floor_count', models.IntegerField(verbose_name='No. of Floors')),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('regd_no', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('roll_no', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('branch', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('pwd', models.BooleanField(default=False)),
                ('community', models.CharField(blank=True, max_length=25, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.MinLengthValidator(4)])),
                ('dob', models.DateField(validators=[institute.validators.date_no_future])),
                ('blood_group', models.CharField(blank=True, max_length=25, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, validators=[institute.validators.numeric_only])),
                ('parents_phone', models.CharField(max_length=10, validators=[institute.validators.numeric_only])),
                ('emergency_phone', models.CharField(blank=True, max_length=10, null=True, validators=[institute.validators.numeric_only])),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=institute.models.Student.photo_storage_path)),
                ('is_hosteller', models.BooleanField(default=True)),
                ('outing_rating', models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=3)),
                ('discipline_rating', models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=3)),
                ('specialization', models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('M.Tech.', 'M.Tech.'), ('MS(Research)', 'MS(Research)'), ('Ph.D', 'Ph.D'), ('Project Staff', 'Project Staff'), ('Interns', 'Interns'), ('Others', 'Others')], max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Caretaker', 'Caretaker'), ('Warden', 'Warden'), ('Deputy Chief-Warden Boys', 'Deputy Chief-Warden Boys'), ('Deputy Chief-Warden Girls', 'Deputy Chief-Warden Girls'), ('Chief-Warden', 'Chief-Warden')], max_length=25)),
                ('phone', models.CharField(max_length=10, validators=[institute.validators.numeric_only])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.block')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(null=True, upload_to=institute.models.Announcements.announcement_file_storage)),
                ('officials_only', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
