# Generated by Django 4.0.4 on 2022-05-19 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_auto_20210112_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regd_no',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
