# Generated by Django 4.0.4 on 2022-06-21 13:30

from django.db import migrations, models
import institute.models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_student_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(null=True, upload_to=institute.models.Announcements.announcement_file_storage)),
            ],
        ),
    ]
