# Generated by Django 4.0.4 on 2022-06-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_announcements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rating',
            new_name='outing_rating',
        ),
        migrations.AddField(
            model_name='student',
            name='discipline_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
