# Generated by Django 4.0.4 on 2022-06-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0015_student_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('M.Tech.', 'M.Tech.'), ('MS(Research)', 'MS(Research)'), ('Ph.D', 'Ph.D'), ('Project Staff', 'Project Staff'), ('Interns', 'Interns'), ('Others', 'Others')], max_length=15),
        ),
    ]
