# Generated by Django 4.0.4 on 2022-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0020_alter_announcements_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='designation',
            field=models.CharField(choices=[('Caretaker', 'Caretaker'), ('Warden', 'Warden'), ('Deputy Chief-Warden Boys', 'Deputy Chief-Warden Boys'), ('Deputy Chief-Warden Girls', 'Deputy Chief-Warden Girls'), ('Chief-Warden', 'Chief-Warden')], max_length=25),
        ),
    ]
